services:
  - name: postgres:13.5
    alias: postgres

variables:
  POSTGRES_DB: "test_db"
  POSTGRES_USER: "user"
  POSTGRES_PASSWORD: "password"
  POSTGRES_HOST: "postgres"

before_script:
  - apt-get update -qq && apt-get install -y -qq postgresql-client
  - python -m pip install --upgrade pip
  - pip install -r requirements.txt

stages:
  - flake8
  - tests

flake8-check:
  stage: flake8
  image: python:3.9
  script:
    - flake8 .

django_tests:
  stage: tests
  image: python:3.9
  script:
    - cd src
    - python3 manage.py test
