services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: api_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

    networks:
      - main_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d api_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  api:
    build: .
    environment:
      POSTGRES_DB: api_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: db
      DJANGO_DEBUG: ${DJANGO_DEBUG}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./api/src/media:/app/src/media
    networks:
      - main_network

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - main_network
    volumes:
      - ./api/src/media:/app/src/media

volumes:
  postgres_data:

networks:
  main_network:
    driver: bridge